spring.datasource.url=jdbc:postgresql://dpg-d74lg5pr0fns73d1fkko-a:5432/mygram_db_20hw
spring.datasource.username=mygram_db_20hw_user
spring.datasource.password=f50yWB5Ty8ZyigdTXCWJ6NIdwif27uxX

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true